SET(CPP_FILES 
source/mapITKObjectToObjectMetricControlInterface.cpp
source/mapITKObjectToObjectOptimizerControlInterface.cpp
)

SET(H_FILES 
include/mapITKImageRegistrationV4Algorithm.h
include/mapITKImageRegistrationV4AlgorithmInterface.h
include/mapITKObjectToObjectMetricControlBase.h
include/mapITKObjectToObjectMetricControlInterface.h
include/mapITKObjectToObjectOptimizerControlBase.h
include/mapITKObjectToObjectOptimizerControlInterface.h
)

SET(TPP_FILES
include/mapITKImageRegistrationV4Algorithm.tpp
include/mapITKImageRegistrationV4AlgorithmInterface.tpp
include/mapITKObjectToObjectMetricControlBase.tpp
include/mapITKObjectToObjectOptimizerControlBase.tpp
)

SET(TEST_CPP_FILES
)